version: "3.9"

services:
  api:
    container_name: caFastapi
    build: ./
    # command: uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8008
    command: sh /app/scripts/start.sh
    ports:
      - "8000:8008"
    env_file:
      - .env.prod
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: caPostgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redisdb:
    container_name: redis_auth
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheusdata:/prometheus
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   volumes:
  #     - grafanadata:/var/lib/grafana
  #   ports:
  #     - "3000:3000"
  
  # loki:
  #   image: grafana/loki:2.9.0
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   volumes:
  #     - ./loki_settings/loki-config.yaml:/etc/loki/local-config.yaml


  # promtail:
  #   image: grafana/promtail:2.9.0
  #   volumes:
  #     - promlogs:/var/log
  #     - ./loki_settings/promtail-config.yaml:/etc/promtail/config.yml
  #   command: -config.file=/etc/promtail/config.yml


volumes:
  postgres_db:
  redisdata:
  # prometheusdata:
  # grafanadata:
  # promlogs: